"""Structured alert object used throughout the IDS pipeline.

IDSAlert carries metadata, severity, rule identifiers, and evidence for each
alert generated by the detection engine.
"""

# src/ids/alert.py

from dataclasses import dataclass, field
from typing import Dict, Any
import time


@dataclass
class IDSAlert:
    """
    Core structured alert object used across the IDS pipeline.
    Every detection rule returns this object instead of printing.
    """

    alert_type: str
    msg_id: int
    ecu: str
    severity: str

    # Human-readable explanation
    reason: str

    # Rule identifier (important for debugging + evaluation)
    rule: str

    # Evidence used to trigger the alert (critical for explainability)
    evidence: Dict[str, Any]

    # Automatic timestamp
    timestamp: float = field(default_factory=time.time)

    def to_dict(self):
        """
        Converts alert into JSON-serializable format.
        Useful for logs, evaluation, and reports.
        """
        return {
            "timestamp": self.timestamp,
            "ecu": self.ecu,
            "msg_id": hex(self.msg_id),
            "alert_type": self.alert_type,
            "severity": self.severity,
            "reason": self.reason,
            "rule": self.rule,
            "evidence": self.evidence,
        }

    def __str__(self):
        """
        Lightweight human-readable representation (console/debugging).
        """
        return f"[{self.alert_type}] {self.reason} | ECU={self.ecu}"
